name: Go test
on:
  push:
    branches: 
      - dev
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v2

      
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      
      - name: go dependencies 
        run: go get -v -t -d ./...
      
      - name: go test 
        run: go test -race -v -cover -coverprofile=coverage.out ./...
        
      - name: upload coverage data
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./src/github.com/${{ github.repository }}/coverage.out
        
